### ISSUE TITLE
Error handling when receiving duplicate metrics

### ISSUE THREAD

**Issue by PhSchmitt** [gustonator/goodwe-prometheus-exporter#6]
It seems that my inverter is sending duplicate data which causes the exporter to crash:

python src/exporter.py --port 8787 --interval 30 --inverter $IP

GOODWE DATA EXPORTER v1.4.4

polling interval:		30s
inverter scrape IP:		$IP
total PV power: 		xxxxW
spot price scrape: 		Disabled
fixed energy price: 		0.2 eur/KW
exporter started on port:	8787

Traceback (most recent call last):
  File "/home/philipp/goodwe/goodwe-prometheus-exporter/src/exporter.py", line 242, in main
    inverter_metrics.run_metrics_loop()
  File "/home/philipp/goodwe/goodwe-prometheus-exporter/src/exporter.py", line 158, in run_metrics_loop
    self.collector_register()
  File "/home/philipp/goodwe/goodwe-prometheus-exporter/src/exporter.py", line 154, in collector_register
    asyncio.run(create_collector_registers())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/philipp/goodwe/goodwe-prometheus-exporter/src/exporter.py", line 143, in create_collector_registers
    self.g.append(Gauge(sensor.id_, sensor.name))
  File "/home/philipp/.local/lib/python3.10/site-packages/prometheus_client/metrics.py", line 399, in __init__
    super().__init__(
  File "/home/philipp/.local/lib/python3.10/site-packages/prometheus_client/metrics.py", line 156, in __init__
    registry.register(self)
  File "/home/philipp/.local/lib/python3.10/site-packages/prometheus_client/registry.py", line 43, in register
    raise ValueError(
ValueError: Duplicated timeseries in CollectorRegistry: {'meter_e_total_exp'}

when running the get-inverter-data, one can see that "meter_e_total_exp" exists in fact twice in the output

python scripts/get-inverter-data.py  | grep meter_e_total_exp
meter_e_total_exp: 		 Meter Total Energy (export) = 0.31 kWh
meter_e_total_exp1: 		 Meter Total Energy (export) L1 = 1.37 kWh
meter_e_total_exp2: 		 Meter Total Energy (export) L2 = 0.91 kWh
meter_e_total_exp3: 		 Meter Total Energy (export) L3 = 5.9 kWh
meter_e_total_exp: 		 Meter Total Energy (export) = 0.31 kWh

Suggestion: add error handling, that in case of duplicate/multiple entries in the data, one will be taken and the others will be ignored

**Comment by gustonator** [comment]
Hi,,
what type of inverter do you have? I'm just curious, cause it's a bit weird, that the inverter exports 2 identical metrics

**Comment by PhSchmitt** [comment]
Hi,
it's a GW20K-ET

**Comment by gustonator** [comment]
fixed in https://github.com/gustonator/goodwe-prometheus-exporter/releases/tag/v1.4.5
